# Create and evaluate a corpus of books

The corpus is taken from the works-registry, and the evaluation selects books that belong to different epochs, where each epoch is defined by the variable `matrix`. This variable contains a dataframe with columns corresponding to epochs and rows are words with different weights within the epoch.

In [51]:
import dhlab.module_update as mu
import dhlab.text as dh
import pandas as pd
import verk as v
import evaluate_corpus as ev
import json

In [3]:
mu.css()

In [4]:
matrix = pd.read_csv("old_vs_new_word_list.csv", index_col = 0)

The process is this

1. Create a matrix 
2. Find works
3. Evaluate the works against the matrix
4. Create a parallell corpus from the evaluation

Create a list of books from know authors or books. This can be done by an exhaustive search or by more contentrated search.

In [6]:
authors = ["bjørnstjerne bjørnson",  "cora sandel", "goethe", "nietsche", "henrik ibsen", "amalie skram", "alexander kielland", "jonas lie", "camilla collett"]

authors = [ "cora sandel"]

In [7]:
author_corpus = {
    auth: dh.Corpus(doctype="digibok", author= auth, limit = 1000, to_year = 1920) for auth in authors
}

Here is what the `author_corpus` looks like

In [22]:
author_corpus[authors[0]].corpus[['urn', 'authors', 'year', 'title']].sample(5)

,urn,authors,year,title
211,URN:NBN:no-nb_digibok_2011103124023,"Bjørnson , Bjørnstjerne",1873,Fortællinger. 1
258,URN:NBN:no-nb_digibok_2014120308100,"Bjørnson , Bjørnstjerne / Dietrichson , L. (Lo...",1907,Taler
103,URN:NBN:no-nb_digibok_2008060613002,"Bjørnson , Bjørnstjerne",1872,Sangen har Lysning
107,URN:NBN:no-nb_digibok_2008060613006,"Bjørnson , Bjørnstjerne",1872,Ved kirke-sanger A. Reitan's jordefærd den 4de...
36,URN:NBN:no-nb_digibok_2016012129003,"Bjørnson , Bjørnstjerne",1861,Kong Sverre

Find the works identifiers, here stored in the variable `works`, from the list of authors, and then looping through the titles.

In [23]:
works = []
for a in author_corpus: 
    for t in author_corpus[a].corpus.title:
        try:
            works.extend(v.find_works(a, t)['id'].values)
        except:
            pass

From this list of different works a parallell corpus is created, using the matrix to find modernized versions.

In [8]:
import importlib
importlib.reload(v)
importlib.reload(ev)

Go through the works list and see if there are URNs in the list. Keep those works with more than one URN

In [24]:
len(works)

384

In [25]:
parallel_candidates = {works_id: v.urns_for_works(works_id) for works_id in works}

In [26]:
candidates = {x:parallel_candidates[x] for x in parallel_candidates if len(parallel_candidates[x]) > 1}

In [39]:
candidates[list(candidates.keys())[3]]

['URN:NBN:no-nb_digibok_2012070905001',
 'URN:NBN:no-nb_digibok_2011031012001',
 'URN:NBN:no-nb_digibok_2012070408109',
 'URN:NBN:no-nb_digibok_2010021803059',
 'URN:NBN:no-nb_digibok_2006082900066',
 'URN:NBN:no-nb_digibok_2008051504087',
 'URN:NBN:no-nb_digibok_2009062204013',
 'URN:NBN:no-nb_digibok_2006082400043',
 'URN:NBN:no-nb_digibok_2008052204119',
 'URN:NBN:no-nb_digibok_2008061900071',
 'URN:NBN:no-nb_digibok_2010070106207',
 'URN:NBN:no-nb_digibok_2010032213006']

In [61]:
import importlib
importlib.reload(ev)

In [62]:
c = dh.CorpusFromIdentifiers(candidates[list(candidates.keys())[2]])

In [63]:
c.corpus

,dhlabid,title,authors,urn,oaiid,sesamid,isbn10,city,timestamp,year,publisher,langs,subjects,ddc,genres,literaryform,doctype
0,100017774,Jeg velger meg april! : 95 dikt,"Bjørnson , Bjørnstjerne / Jacobsen , Rolf",URN:NBN:no-nb_digibok_2009022600051,oai:nb.bibsys.no:990006123834702202,c4d8df04e679252120e9e17104be3460,8252536239 / 8205270953,[Oslo],20000101,2000,Gyldendal,nob,,839.821,fiction,Skjønnlitteratur,digibok
1,100523238,Jeg velger meg april! : 95 dikt,"Bjørnson , Bjørnstjerne / Jacobsen , Rolf",URN:NBN:no-nb_digibok_2008060904035,oai:nb.bibsys.no:998221829204702202,70edce0e4d9c819ac708e981510923ec,8205138958,Oslo,19820101,1982,Gyldendal,nob,norske / dikt,839.91,fiction,Skjønnlitteratur,digibok

In [64]:
ev.evaluate_corpus_norwegian(corpus = c, matrix=matrix, top_number = 10)

{'URN:NBN:no-nb_digibok_2008060904035': ('1800', 0.3838943153285951),
 'URN:NBN:no-nb_digibok_2009022600051': ('1800', 0.38981935504134235)}

In [65]:
evals = {}
for worksid in candidates:
    try:
        evals[worksid] = ev.evaluate_corpus_norwegian(corpus = dh.CorpusFromIdentifiers(candidates[worksid]), matrix = matrix)
    except KeyboardInterrupt:
        break
    except:
        pass

In [66]:
triple = {}
for i in evals:
    data = evals[i]
    old = [x for x in data if int(data[x][0]) <= 1900 ]
    new = [x for x in data if int(data[x][0]) > 1900 ] 
    if old != [] and new != []:
        triple[i] = (old, new)

In [67]:
triple

{'eafd78267a468b309fb4eddc1cb3840479fcdad9089094b8ae075a1fc749242e': (['URN:NBN:no-nb_digibok_2008060904035',
   'URN:NBN:no-nb_digibok_2009022600051'],
  ['URN:NBN:no-nb_digibok_2008071812002']),
 '4405c68f5bb3e077ec405b10d5c5df9ed097eb20adaddfdc052d1215a05b1c5c': (['URN:NBN:no-nb_digibok_2006080900015',
   'URN:NBN:no-nb_digibok_2009062200004'],
  ['URN:NBN:no-nb_digibok_2008070812004']),
 '396ddc56ae4b19a533550b9d63df04bd9c25c8675ae3768ac9f1aead4f0e3b56': (['URN:NBN:no-nb_digibok_2008051504087',
   'URN:NBN:no-nb_digibok_2011031012001',
   'URN:NBN:no-nb_digibok_2006082400043',
   'URN:NBN:no-nb_digibok_2010070106207',
   'URN:NBN:no-nb_digibok_2006082900066',
   'URN:NBN:no-nb_digibok_2010032213006',
   'URN:NBN:no-nb_digibok_2008052204119',
   'URN:NBN:no-nb_digibok_2009062204013',
   'URN:NBN:no-nb_digibok_2012070905001',
   'URN:NBN:no-nb_digibok_2008061900071'],
  ['URN:NBN:no-nb_digibok_2010021803059',
   'URN:NBN:no-nb_digibok_2012070408109']),
 '262824678d4b0e2d8695df21b6d920c786cd5c019dcb82ad99b458b057e3d243': (['URN:NBN:no-nb_digibok_2008060904035',
   'URN:NBN:no-nb_digibok_2009022600051'],
  ['URN:NBN:no-nb_digibok_2012102107020']),
 '1d4ea7e02197c411eb6670d943664e88beded896e11093af4063c9a5c13d7211': (['URN:NBN:no-nb_digibok_2011031012001',
   'URN:NBN:no-nb_digibok_2008051504087',
   'URN:NBN:no-nb_digibok_2010070106207',
   'URN:NBN:no-nb_digibok_2006082400043',
   'URN:NBN:no-nb_digibok_2008060904035',
   'URN:NBN:no-nb_digibok_2012070905001',
   'URN:NBN:no-nb_digibok_2008061900071',
   'URN:NBN:no-nb_digibok_2009022600051',
   'URN:NBN:no-nb_digibok_2010032213006'],
  ['URN:NBN:no-nb_digibok_2012070408109']),
 '50479b0cfbc89d081154db811ba107c616c1d20bf9e650b898e2d7554bb0f1ab': (['URN:NBN:no-nb_digibok_2011120108006'],
  ['URN:NBN:no-nb_digibok_2008071812003',
   'URN:NBN:no-nb_digibok_2008031404070']),
 '02a6637e43b34acd12443f4d12e62c10166f8ad37941434bcc747782e7dbf16c': (['URN:NBN:no-nb_digibok_2008020500112',
   'URN:NBN:no-nb_digibok_2008070800097'],
  ['URN:NBN:no-nb_digibok_2014092506034',
   'URN:NBN:no-nb_digibok_2008072412003']),
 'e9764ff2f8b1631cbc170f266eb4120cdbcc8f60f6df060f1f0000da19671aac': (['URN:NBN:no-nb_digibok_2011120108006',
   'URN:NBN:no-nb_digibok_2006082800014',
   'URN:NBN:no-nb_digibok_2010070106207',
   'URN:NBN:no-nb_digibok_2006082400043',
   'URN:NBN:no-nb_digibok_2012070905001',
   'URN:NBN:no-nb_digibok_2011031012001',
   'URN:NBN:no-nb_digibok_2008061900071',
   'URN:NBN:no-nb_digibok_2014032738014'],
  ['URN:NBN:no-nb_digibok_2012070408109']),
 '64a2844abe6d7b78619b7c6fbb21039e8e9243fdb4a54a1690fc00674bd8a8cb': (['URN:NBN:no-nb_digibok_2011060606014',
   'URN:NBN:no-nb_digibok_2009031600127',
   'URN:NBN:no-nb_digibok_2008081500025'],
  ['URN:NBN:no-nb_digibok_2008040300020']),
 'b2ae35a0bda31027cd849ac1b0eb0e5b0199de0130010f6e7fd7bb2b640b6a25': (['URN:NBN:no-nb_digibok_2010091320016',
   'URN:NBN:no-nb_digibok_2007091301037',
   'URN:NBN:no-nb_digibok_2010083123001',
   'URN:NBN:no-nb_digibok_2007082204013',
   'URN:NBN:no-nb_digibok_2011030820014',
   'URN:NBN:no-nb_digibok_2008021100060',
   'URN:NBN:no-nb_digibok_2008101004039',
   'URN:NBN:no-nb_digibok_2010091720001',
   'URN:NBN:no-nb_digibok_2010061720011',
   'URN:NBN:no-nb_digibok_2010101120010',
   'URN:NBN:no-nb_digibok_2008090100044',
   'URN:NBN:no-nb_digibok_2011063022001'],
  ['URN:NBN:no-nb_digibok_2009040303005',
   'URN:NBN:no-nb_digibok_2010031610004',
   'URN:NBN:no-nb_digibok_2010101120011',
   'URN:NBN:no-nb_digibok_2010032312002',
   'URN:NBN:no-nb_digibok_2010052520003',
   'URN:NBN:no-nb_digibok_2010032212003',
   'URN:NBN:no-nb_digibok_2010090120014',
   'URN:NBN:no-nb_digibok_2010081720014']),
 '6815fba8d19d5d4eb7a89821ae40106cc19d02d569fa450fc840e2f29e43a975': (['URN:NBN:no-nb_digibok_2010042312002',
   'URN:NBN:no-nb_digibok_2010082422018',
   'URN:NBN:no-nb_digibok_2008021104056',
   'URN:NBN:no-nb_digibok_2011012412004',
   'URN:NBN:no-nb_digibok_2008101000054',
   'URN:NBN:no-nb_digibok_2013083008076',
   'URN:NBN:no-nb_digibok_2010051923004',
   'URN:NBN:no-nb_digibok_2011063022001'],
  ['URN:NBN:no-nb_digibok_2012112324002',
   'URN:NBN:no-nb_digibok_2010061720018',
   'URN:NBN:no-nb_digibok_2010051812002',
   'URN:NBN:no-nb_digibok_2006112001032',
   'URN:NBN:no-nb_digibok_2010060420013',
   'URN:NBN:no-nb_digibok_2010040812003']),
 '1ed3479af350aea14edb4e733745c3a5435d631fa820cda7fdfe3971c6ba6ded': (['URN:NBN:no-nb_digibok_2010061720012',
   'URN:NBN:no-nb_digibok_2007112300065',
   'URN:NBN:no-nb_digibok_2006080900005',
   'URN:NBN:no-nb_digibok_2008061900093',
   'URN:NBN:no-nb_digibok_2008101004039',
   'URN:NBN:no-nb_digibok_2008021100060',
   'URN:NBN:no-nb_digibok_2011063022001',
   'URN:NBN:no-nb_digibok_2011070620008',
   'URN:NBN:no-nb_digibok_2008040204014'],
  ['URN:NBN:no-nb_digibok_2010081720014',
   'URN:NBN:no-nb_digibok_2010101120011']),
 '289786d59a295c86a001f731a664e4071cf20fb43b217bd4c65d52acfcbc0434': (['URN:NBN:no-nb_digibok_2008040200071',
   'URN:NBN:no-nb_digibok_2007043004076',
   'URN:NBN:no-nb_digibok_2011063022001',
   'URN:NBN:no-nb_digibok_2007111900125',
   'URN:NBN:no-nb_digibok_2010061720014',
   'URN:NBN:no-nb_digibok_2010101120010',
   'URN:NBN:no-nb_digibok_2008021104056',
   'URN:NBN:no-nb_digibok_2013050224087',
   'URN:NBN:no-nb_digibok_2008101004039'],
  ['URN:NBN:no-nb_digibok_2010081720014',
   'URN:NBN:no-nb_digibok_2010090120014']),
 'e883f4ae1a7d9e01c13a536405542e2295830c3065fbd263bff432a84477e505': (['URN:NBN:no-nb_digibok_2015050408113',
   'URN:NBN:no-nb_digibok_2009031600022',
   'URN:NBN:no-nb_digibok_2008030704048',
   'URN:NBN:no-nb_digibok_2008011004165',
   'URN:NBN:no-nb_digibok_2011063022001',
   'URN:NBN:no-nb_digibok_2012072708064'],
  ['URN:NBN:no-nb_digibok_2006112001032',
   'URN:NBN:no-nb_digibok_2010061720010',
   'URN:NBN:no-nb_digibok_2013050224047']),
 '788c0345d7622ff5b8de8eee60ae08c304a6d70204ef6f9ec119e413bd309ad8': (['URN:NBN:no-nb_digibok_2010060820009',
   'URN:NBN:no-nb_digibok_2011063022001',
   'URN:NBN:no-nb_digibok_2012072708064',
   'URN:NBN:no-nb_digibok_2010081720016',
   'URN:NBN:no-nb_digibok_2009031600032',
   'URN:NBN:no-nb_digibok_2010081920021',
   'URN:NBN:no-nb_digibok_2008021104045',
   'URN:NBN:no-nb_digibok_2009042203004',
   'URN:NBN:no-nb_digibok_2010061412002'],
  ['URN:NBN:no-nb_digibok_2014080424009',
   'URN:NBN:no-nb_digibok_2010052820003',
   'URN:NBN:no-nb_digibok_2011072012004',
   'URN:NBN:no-nb_digibok_2010090320026',
   'URN:NBN:no-nb_digibok_2010051812001',
   'URN:NBN:no-nb_digibok_2010061720009']),
 'b363d3b1813fd1aff37cc6ed6fb8572cc316d8da78dc4b00e682aa4995d6a0f0': (['URN:NBN:no-nb_digibok_2007121004079',
   'URN:NBN:no-nb_digibok_2008030704048',
   'URN:NBN:no-nb_digibok_2011063022001',
   'URN:NBN:no-nb_digibok_2012072708064',
   'URN:NBN:no-nb_digibok_2013050224106',
   'URN:NBN:no-nb_digibok_2009031600022',
   'URN:NBN:no-nb_digibok_2007120404016',
   'URN:NBN:no-nb_digibok_2009033103042'],
  ['URN:NBN:no-nb_digibok_2010061223006']),
 'dbcc5c217138289b98c0f702b316400aa08ba36e21406d9f66e0d1ebe8ea0817': (['URN:NBN:no-nb_digibok_2010111706107',
   'URN:NBN:no-nb_digibok_2011012412004',
   'URN:NBN:no-nb_digibok_2010081720016',
   'URN:NBN:no-nb_digibok_2009041504059',
   'URN:NBN:no-nb_digibok_2012072708128'],
  ['URN:NBN:no-nb_digibok_2006121401009',
   'URN:NBN:no-nb_digibok_2009042204111']),
 '473efa345cf19d497edfb1423793fead767267973f37f5d1419ad6ee14b1d69e': (['URN:NBN:no-nb_digibok_2011063022001',
   'URN:NBN:no-nb_digibok_2010061403053',
   'URN:NBN:no-nb_digibok_2013083008076',
   'URN:NBN:no-nb_digibok_2010082422008',
   'URN:NBN:no-nb_digibok_2009031600032',
   'URN:NBN:no-nb_digibok_2008021104045'],
  ['URN:NBN:no-nb_digibok_2010061720008']),
 'ece4e42fd565f64bf418c453d5634e53ade8db56961d2fca768e7b737581dff6': (['URN:NBN:no-nb_digibok_2011063022001',
   'URN:NBN:no-nb_digibok_2010061720011',
   'URN:NBN:no-nb_digibok_2008021100060',
   'URN:NBN:no-nb_digibok_2013050224074',
   'URN:NBN:no-nb_digibok_2009031600022',
   'URN:NBN:no-nb_digibok_2007111201018',
   'URN:NBN:no-nb_digibok_2010021910002'],
  ['URN:NBN:no-nb_digibok_2010081720014',
   'URN:NBN:no-nb_digibok_2009040303005']),
 'd551b482fac3a14019069279cb5e76aed23f6add5a782ff2fa62bdaf098a8ebf': (['URN:NBN:no-nb_digibok_2010111910004',
   'URN:NBN:no-nb_digibok_2010111910005'],
  ['URN:NBN:no-nb_digibok_2009042204111']),
 '515c6300182b4b40221c7c3aee848f2f3777584257559a759a7f3d294cec8973': (['URN:NBN:no-nb_digibok_2008022704045',
   'URN:NBN:no-nb_digibok_2011071408167',
   'URN:NBN:no-nb_digibok_2008051500108',
   'URN:NBN:no-nb_digibok_2007081700078',
   'URN:NBN:no-nb_digibok_2010100603002',
   'URN:NBN:no-nb_digibok_2007082801022'],
  ['URN:NBN:no-nb_digibok_2012050806006',
   'URN:NBN:no-nb_digibok_2011062208057']),
 '81696383a539cf9621f9902a8eb117f87148a6e9645057a7293eea4eb1c87256': (['URN:NBN:no-nb_digibok_2012092608175',
   'URN:NBN:no-nb_digibok_2007121104093',
   'URN:NBN:no-nb_digibok_2015052108175',
   'URN:NBN:no-nb_digibok_2010100603002'],
  ['URN:NBN:no-nb_digibok_2009021603021']),
 'b3dd16597159fcbfc7c0ada8fc02f48759bd254017f483d84a1de157994bd29e': (['URN:NBN:no-nb_digibok_2010100603002',
   'URN:NBN:no-nb_digibok_2014022708239'],
  ['URN:NBN:no-nb_digibok_2012050806006',
   'URN:NBN:no-nb_digibok_2013082008056',
   'URN:NBN:no-nb_digibok_2011062208057']),
 'dd782c32085d3f4d6a1ba5aa71699929958c3b458384bf290078b1cb5bd52bf3': (['URN:NBN:no-nb_digibok_2006081000050',
   'URN:NBN:no-nb_digibok_2007110601069',
   'URN:NBN:no-nb_digibok_2010100603002',
   'URN:NBN:no-nb_digibok_2009050704080',
   'URN:NBN:no-nb_digibok_2011070620017',
   'URN:NBN:no-nb_digibok_2009051304105'],
  ['URN:NBN:no-nb_digibok_2012050806006',
   'URN:NBN:no-nb_digibok_2014102108198']),
 '5b2057854505953807486effa5bd382654e9cb54abd0d6f7734ab588b75ce4b5': (['URN:NBN:no-nb_digibok_2009021004142',
   'URN:NBN:no-nb_digibok_2010091608022',
   'URN:NBN:no-nb_digibok_2012050806035',
   'URN:NBN:no-nb_digibok_2012012308213',
   'URN:NBN:no-nb_digibok_2008021204058',
   'URN:NBN:no-nb_digibok_2010070505038'],
  ['URN:NBN:no-nb_digibok_2011022220001',
   'URN:NBN:no-nb_digibok_2009102010006',
   'URN:NBN:no-nb_digibok_2014071606003']),
 'b8da3a53ef9fbb28bf2d85a9ffc5ffc0955ecb91e27d2adc872d6b8f4f445a63': (['URN:NBN:no-nb_digibok_2008021804002',
   'URN:NBN:no-nb_digibok_2008081200104',
   'URN:NBN:no-nb_digibok_2008031200066',
   'URN:NBN:no-nb_digibok_2011070620020',
   'URN:NBN:no-nb_digibok_2011033012001',
   'URN:NBN:no-nb_digibok_2009021004142',
   'URN:NBN:no-nb_digibok_2010091608022',
   'URN:NBN:no-nb_digibok_2014090408112',
   'URN:NBN:no-nb_digibok_2013053008055',
   'URN:NBN:no-nb_digibok_2006082800126',
   'URN:NBN:no-nb_digibok_2008092504005',
   'URN:NBN:no-nb_digibok_2012012308213',
   'URN:NBN:no-nb_digibok_2010102906050'],
  ['URN:NBN:no-nb_digibok_2014102306003',
   'URN:NBN:no-nb_digibok_2014101408243',
   'URN:NBN:no-nb_digibok_2013071508148']),
 'b11e045249061d23ef785c7515ccad461a53bd7c14320dc5cb584579b6515679': (['URN:NBN:no-nb_digibok_2008021100101',
   'URN:NBN:no-nb_digibok_2008090300007',
   'URN:NBN:no-nb_digibok_2012012308213',
   'URN:NBN:no-nb_digibok_2010090208039',
   'URN:NBN:no-nb_digibok_2011112808046'],
  ['URN:NBN:no-nb_digibok_2008121603024',
   'URN:NBN:no-nb_digibok_2014073005040',
   'URN:NBN:no-nb_digibok_2014071506052']),
 '90b9cf2c20ba3ea95714c7a5f51550153db149cdd73e226a6fc200d3245feeb1': (['URN:NBN:no-nb_digibok_2009101510003',
   'URN:NBN:no-nb_digibok_2010070505038',
   'URN:NBN:no-nb_digibok_2008021204058',
   'URN:NBN:no-nb_digibok_2009021000130',
   'URN:NBN:no-nb_digibok_2008103004018',
   'URN:NBN:no-nb_digibok_2009102012002',
   'URN:NBN:no-nb_digibok_2012012308213',
   'URN:NBN:no-nb_digibok_2012012008212'],
  ['URN:NBN:no-nb_digibok_2009101510002',
   'URN:NBN:no-nb_digibok_2009092110004',
   'URN:NBN:no-nb_digibok_2009092910004',
   'URN:NBN:no-nb_digibok_2014071606003',
   'URN:NBN:no-nb_digibok_2010050403036',
   'URN:NBN:no-nb_digibok_2014021906296']),
 'f5d955b2abe1c8a65217ba69077392ef7572960aec86cb4b13e64c5fe34996b5': (['URN:NBN:no-nb_digibok_2008021204058',
   'URN:NBN:no-nb_digibok_2012012308213',
   'URN:NBN:no-nb_digibok_2008103004018',
   'URN:NBN:no-nb_digibok_2009021000130',
   'URN:NBN:no-nb_digibok_2010070505038',
   'URN:NBN:no-nb_digibok_2009102012002'],
  ['URN:NBN:no-nb_digibok_2009092110004',
   'URN:NBN:no-nb_digibok_2014071606003',
   'URN:NBN:no-nb_digibok_2014021906296',
   'URN:NBN:no-nb_digibok_2010050403036',
   'URN:NBN:no-nb_digibok_2011062712001']),
 '843403e872fa302fdc640bd1c4994cb32dabb07bd727797e94b103e9c90d7f8c': (['URN:NBN:no-nb_digibok_2008103004018',
   'URN:NBN:no-nb_digibok_2008031200066',
   'URN:NBN:no-nb_digibok_2012012308213',
   'URN:NBN:no-nb_digibok_2009021004142',
   'URN:NBN:no-nb_digibok_2010091608022',
   'URN:NBN:no-nb_digibok_2013053008055'],
  ['URN:NBN:no-nb_digibok_2010050403036',
   'URN:NBN:no-nb_digibok_2014102306003',
   'URN:NBN:no-nb_digibok_2009092312001',
   'URN:NBN:no-nb_digibok_2009092110004']),
 '46abad8d08382817cfaa0af848cfed252b3d586241d834dad7ccbfc0f9ade381': (['URN:NBN:no-nb_digibok_2006082800099',
   'URN:NBN:no-nb_digibok_2012012308213',
   'URN:NBN:no-nb_digibok_2008082904033',
   'URN:NBN:no-nb_digibok_2013053008055',
   'URN:NBN:no-nb_digibok_2010090208035'],
  ['URN:NBN:no-nb_digibok_2006082500032',
   'URN:NBN:no-nb_digibok_2014102306003']),
 '536c0f5cddd2a1f54c3a8f520989d5f35105cda0cce06568bad1ba5115120d72': (['URN:NBN:no-nb_digibok_2010091608022',
   'URN:NBN:no-nb_digibok_2009021004142',
   'URN:NBN:no-nb_digibok_2009111012006',
   'URN:NBN:no-nb_digibok_2008031200066',
   'URN:NBN:no-nb_digibok_2010070505038'],
  ['URN:NBN:no-nb_digibok_2014071606003',
   'URN:NBN:no-nb_digibok_2009111112009']),
 '15c6bc46d364727413e0ff9962a44c9e16d1671cc6e99f98e4a1a87e975facf7': (['URN:NBN:no-nb_digibok_2012041308029',
   'URN:NBN:no-nb_digibok_2008082904033',
   'URN:NBN:no-nb_digibok_2010032213008',
   'URN:NBN:no-nb_digibok_2013053008055',
   'URN:NBN:no-nb_digibok_2008031200066',
   'URN:NBN:no-nb_digibok_2011101208058',
   'URN:NBN:no-nb_digibok_2012010508003',
   'URN:NBN:no-nb_digibok_2007082201033',
   'URN:NBN:no-nb_digibok_2010090208035',
   'URN:NBN:no-nb_digibok_2007102900031',
   'URN:NBN:no-nb_digibok_2014100708075',
   'URN:NBN:no-nb_digibok_2008092504040',
   'URN:NBN:no-nb_digibok_2011031120024'],
  ['URN:NBN:no-nb_digibok_2014102306003']),
 '4b691ca39e2a5db42b9d55e3c2064fce175f97f4f66be89e727a5cc29861dc38': (['URN:NBN:no-nb_digibok_2013053008055',
   'URN:NBN:no-nb_digibok_2008031200066',
   'URN:NBN:no-nb_digibok_2009110310001',
   'URN:NBN:no-nb_digibok_2010032213008',
   'URN:NBN:no-nb_digibok_2014111708093',
   'URN:NBN:no-nb_digibok_2007102900031',
   'URN:NBN:no-nb_digibok_2007082201033',
   'URN:NBN:no-nb_digibok_2010090208035',
   'URN:NBN:no-nb_digibok_2008082904033',
   'URN:NBN:no-nb_digibok_2006082900010'],
  ['URN:NBN:no-nb_digibok_2009102212008',
   'URN:NBN:no-nb_digibok_2014102306003']),
 'fab60f1351fe737ca8c26e23fc82d29a945e98e24d3e4346515b72e9c6284cf4': (['URN:NBN:no-nb_digibok_2011101408135',
   'URN:NBN:no-nb_digibok_2010032213007'],
  ['URN:NBN:no-nb_digibok_2012060106021',
   'URN:NBN:no-nb_digibok_2010052806015']),
 '27455af1a1109f1655988c8e37952b433781cac14b92cc2e280349a06020cdac': (['URN:NBN:no-nb_digibok_2012030208159'],
  ['URN:NBN:no-nb_digibok_2006082900118']),
 '943d032ef0f13a06385a7912cb7115beb42981425fbb06f467f29309e464e884': (['URN:NBN:no-nb_digibok_2006081100010'],
  ['URN:NBN:no-nb_digibok_2008062004038']),
 '4db6c6aad543ca7259a37a987c4f0b1bbee1cbf87be6b11fea153fd0df4add3d': (['URN:NBN:no-nb_digibok_2012011808057'],
  ['URN:NBN:no-nb_digibok_2006081700046']),
 'ae1a88bbc0e926087c2713b8e5fe48b1dd03775dfca5a75558380a9216d4fe5e': (['URN:NBN:no-nb_digibok_2007110104005'],
  ['URN:NBN:no-nb_digibok_2014090308001']),
 '84ca64d0270426990a666390b00b5f0d0e254c0c6894bc99ce9124d59e6ab0ca': (['URN:NBN:no-nb_digibok_2006083100104',
   'URN:NBN:no-nb_digibok_2010061403046',
   'URN:NBN:no-nb_digibok_2008080500045',
   'URN:NBN:no-nb_digibok_2011070620010',
   'URN:NBN:no-nb_digibok_2014032108017'],
  ['URN:NBN:no-nb_digibok_2009042112003',
   'URN:NBN:no-nb_digibok_2009042012006']),
 '4f1b0149fcfcb7e614229d6e6987f6d32b1fc7f4933ce02aa7e5d98384d7ad8e': (['URN:NBN:no-nb_digibok_2010070205101',
   'URN:NBN:no-nb_digibok_2006080900004',
   'URN:NBN:no-nb_digibok_2007110104005',
   'URN:NBN:no-nb_digibok_2008080500045',
   'URN:NBN:no-nb_digibok_2011120508051',
   'URN:NBN:no-nb_digibok_2012021308024',
   'URN:NBN:no-nb_digibok_2008011104033',
   'URN:NBN:no-nb_digibok_2015031106069',
   'URN:NBN:no-nb_digibok_2011070620010'],
  ['URN:NBN:no-nb_digibok_2006082400077',
   'URN:NBN:no-nb_digibok_2014100807576',
   'URN:NBN:no-nb_digibok_2014102108223',
   'URN:NBN:no-nb_digibok_2014050908107',
   'URN:NBN:no-nb_digibok_2014021208010']),
 '5f966dca3672b0948f66c148a8259562bb33807cb467ce14e86cdb08d206812a': (['URN:NBN:no-nb_digibok_2010102906097',
   'URN:NBN:no-nb_digibok_2014092308143',
   'URN:NBN:no-nb_digibok_2008070700052',
   'URN:NBN:no-nb_digibok_2008022001004',
   'URN:NBN:no-nb_digibok_2012112206221',
   'URN:NBN:no-nb_digibok_2011070620007',
   'URN:NBN:no-nb_digibok_2006083100087',
   'URN:NBN:no-nb_digibok_2014073108005'],
  ['URN:NBN:no-nb_digibok_2010111506037',
   'URN:NBN:no-nb_digibok_2009072812002',
   'URN:NBN:no-nb_digibok_2014111008005',
   'URN:NBN:no-nb_digibok_2009072212001',
   'URN:NBN:no-nb_digibok_2009072912001',
   'URN:NBN:no-nb_digibok_2014092608039',
   'URN:NBN:no-nb_digibok_2011032520038',
   'URN:NBN:no-nb_digibok_2009071712001',
   'URN:NBN:no-nb_digibok_2009072112001',
   'URN:NBN:no-nb_digibok_2013042508156']),
 '366df9fd51cf352330fffdf35eb5cad8fec128e634af69f826897090a27975e6': (['URN:NBN:no-nb_digibok_2015091506126',
   'URN:NBN:no-nb_digibok_2006083100087'],
  ['URN:NBN:no-nb_digibok_2007122100036',
   'URN:NBN:no-nb_digibok_2008040104103',
   'URN:NBN:no-nb_digibok_2009072412002',
   'URN:NBN:no-nb_digibok_2014092608039',
   'URN:NBN:no-nb_digibok_2009072812001',
   'URN:NBN:no-nb_digibok_2006111400028',
   'URN:NBN:no-nb_digibok_2008061600099'])}

In [68]:
with open("ny_gammel_verksid.json", "w") as f:
    json.dump(triple, f)

In [75]:
dh.CorpusFromIdentifiers([x for y in triple.values() for z in y for x in z]).corpus["authors title year langs".split()].style